server:
  port: 8090

spring:
  application:
    name: life-manager
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5434}/life_manager
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      org.hibernate:
        envers:
          autoRegisterListeners: true
          audit_table_suffix: _history
          default_schema: life_manager_history
          store_data_at_delete: true
          revision_field_name: revision_id
          revision_type_field_name: revision_type
          revision_sequence_name: life_manager_history.revinfo_seq
        hibernate:
          default_schema: life_manager
          show_sql: ${SHOW_SQL:true}
          format_sql: ${FORMAT_SQL:true}
          highlight_sql: ${HIGHLIGHT_SQL:true}
          session.events.log.LOG_QUERIES_SLOWER_THAN_MS: ${SLOW_SQL_QUERY_INDICATOR_MS:1500}
          hbm2ddl:
            auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minio_admin}
  secret-key: ${MINIO_SECRET_KEY:minio_admin}
  bucket-name: ${MINIO_BUCKET_NAME:errors-bucket}
  auto-create-bucket: ${MINIO_AUTO_CREATE_BUCKET:true}

error-storage:
  file-path: ${ERROR_STORAGE_FILE_PATH:./error-events}